[package]
name = "nil-client"

[package.version]
workspace = true

[package.description]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
bytes = "1.10"
futures = "0.3"
http = "1.2"
itertools = "0.14"
local-ip-address = "=0.6.3"
serde_json = "1.0"
thiserror = "2.0"

[dependencies.nil-core]
version = "*"
path = "../nil-core"

[dependencies.nil-util]
version = "*"
path = "../nil-util"

[dependencies.reqwest]
version = "0.12"
features = ["json", "rustls-tls"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.43"
default-features = false
features = ["time"]

[dependencies.tokio-tungstenite]
version = "0.26"
features = []
