[package]
name = "nil-server"
version = "0.1.1"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license-file]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.axum]
workspace = true

[dependencies.derive_more]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.itertools]
workspace = true

[dependencies.nil-core]
workspace = true

[dependencies.nil-util]
workspace = true

[dependencies.percent-encoding]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tower-http]
workspace = true

[dependencies.tracing]
workspace = true
