[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
license-file = "./LICENSE"
homepage = "https://nil.dev.br"
repository = "https://github.com/tsukilabs/nil"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>", "Danilo Soares <danilofs18@gmail.com>"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[profile.release-bin]
inherits = "release"
strip = "symbols"

[profile.preview]
inherits = "release"
codegen-units = 16
lto = "off"
opt-level = 0
debug = true
debug-assertions = true

[workspace.dependencies]
anyhow = "1.0"
bon = "3.6"
bytes = "1.10"
futures = "0.3"
http = "1.3"
itertools = "0.14"
js-sys = "0.3"
local-ip-address = "=0.6.5"
proc-macro2 = "1.0"
quote = "1.0"
remain = "0.2"
serde_json = "1.0"
tauri-plugin-clipboard-manager = "2.3"
tauri-plugin-dialog = "2.3"
tauri-plugin-fs = "2.4"
tauri-plugin-persisted-scope = "2.3"
tauri-plugin-process = "2.3"
tauri-plugin-single-instance = "2.3"
tauri-plugin-window-state = "2.3"
thiserror = "2.0"
tokio-tungstenite = "0.27"
wasm-bindgen = "0.2"

[workspace.dependencies.axum]
version = "0.8"
features = ["macros", "ws"]

[workspace.dependencies.derive_more]
version = "2.0"
features = ["deref", "deref_mut", "display", "from"]

[workspace.dependencies.indexmap]
version = "2.10"
features = ["serde"]

[workspace.dependencies.jiff]
version = "0.2"
features = ["serde"]

[workspace.dependencies.mlua]
version = "0.10"
features = ["error-send", "lua54", "send", "serialize", "vendored"]

[workspace.dependencies.nil-client]
version = "*"
path = "./crates/nil-client"

[workspace.dependencies.nil-core]
version = "*"
path = "./crates/nil-core"

[workspace.dependencies.nil-core-macros]
version = "*"
path = "./crates/nil-core-macros"

[workspace.dependencies.nil-future]
version = "*"
path = "./crates/nil-future"

[workspace.dependencies.nil-num]
version = "*"
path = "./crates/nil-num"

[workspace.dependencies.nil-num-macros]
version = "*"
path = "./crates/nil-num-macros"

[workspace.dependencies.nil-server]
version = "*"
path = "./crates/nil-server"

[workspace.dependencies.nil-util]
version = "*"
path = "./crates/nil-util"

[workspace.dependencies.reqwest]
version = "0.12"
default-features = false
features = ["charset", "json", "rustls-tls"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.strum]
version = "0.27"
features = ["derive"]

[workspace.dependencies.syn]
version = "2.0"
features = ["derive"]

[workspace.dependencies.tauri-plugin-prevent-default]
version = "2.1"
features = ["unstable-windows"]

[workspace.dependencies.tokio]
version = "1.46"
features = ["full"]

[workspace.dependencies.tower-http]
version = "0.6"
features = ["trace"]

[workspace.dependencies.tracing]
version = "0.1"
features = ["release_max_level_off"]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["ansi", "chrono", "env-filter", "fmt", "parking_lot", "registry", "smallvec", "std"]

[workspace.dependencies.web-sys]
version = "0.3"
features = ["console"]

[workspace.lints.rust]
async_fn_in_trait = "allow"
dangling_pointers_from_temporaries = "deny"
unfulfilled_lint_expectations = "deny"
unsafe_op_in_unsafe_fn = "deny"
variant_size_differences = "warn"

[workspace.lints.clippy]
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
clone_on_ref_ptr = "deny"
dbg_macro = "deny"
enum_glob_use = "allow"
filetype_is_file = "deny"
get_unwrap = "deny"
large_enum_variant = "deny"
map_unwrap_or = "allow"
match_wildcard_for_single_variants = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "deny"
module_name_repetitions = "allow"
must_use_candidate = "allow"
needless_borrow = "deny"
needless_for_each = "allow"
rc_buffer = "deny"
rc_mutex = "deny"
rest_pat_in_fully_bound_structs = "deny"
similar_names = "allow"
struct_field_names = "allow"
unnecessary_safety_comment = "deny"
unsafe_derive_deserialize = "allow"
useless_conversion = "deny"

[workspace.lints.clippy.pedantic]
level = "deny"
priority = -1
