[package]
name = "nil-util"
version = "0.1.0"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license-file]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
bytes = "1.10"
serde = "1.0"
serde_json = "1.0"

[dependencies.tauri]
version = "2.6"
default-features = false

[dependencies.tokio]
version = "1.46"
default-features = false
features = []

[dependencies.tracing]
version = "0.1"
features = ["release_max_level_off"]
