[package]
name = "nil-core"
version = "0.1.0"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license-file]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
bon = "3.6"
itertools = "0.14"
remain = "0.2"
thiserror = "2.0"

[dependencies.derive_more]
version = "2.0"
features = ["deref", "deref_mut", "display", "from"]

[dependencies.indexmap]
version = "2.10"
features = ["serde"]

[dependencies.jiff]
version = "0.2"
features = ["serde"]

[dependencies.mlua]
version = "0.10"
features = ["error-send", "lua54", "send", "serialize", "vendored"]

[dependencies.nil-core-macros]
version = "*"
path = "../nil-core-macros"

[dependencies.nil-util]
version = "*"
path = "../nil-util"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.strum]
version = "0.27"
features = ["derive"]

[dependencies.tokio]
version = "1.46"
default-features = false

[dependencies.tracing]
version = "0.1"
features = ["release_max_level_off"]
