[package]
name = "nil-core"
version = "0.1.0"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[lints]
workspace = true

[dependencies]
bon = "3.5"
bytes = "1.10"
itertools = "0.14"
rand = "0.9"
remain = "0.2"
serde_json = "1.0"
thiserror = "2.0"

[dependencies.derive_more]
version = "2.0"
features = ["deref", "deref_mut", "display", "try_unwrap"]

[dependencies.indexmap]
version = "2.9"
features = ["serde"]

[dependencies.nil-core-macros]
version = "*"
path = "../nil-core-macros"

[dependencies.nil-util]
version = "*"
path = "../nil-util"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.strum]
version = "0.27"
features = ["derive"]

[dependencies.tokio]
version = "1.44"
default-features = false
