[package]
name = "nil-core"

[package.version]
workspace = true

[package.description]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[lints]
workspace = true

[dependencies]
bon = "3.3"
itertools = "0.14"
rand = "0.9"
serde_json = "1.0"
thiserror = "2.0"

[dependencies.derive_more]
version = "2.0"
features = ["deref", "deref_mut", "display", "try_unwrap"]

[dependencies.indexmap]
version = "2.7"
features = ["serde"]

[dependencies.nil-macros]
version = "*"
path = "../nil-macros"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.strum]
version = "0.26"
features = ["derive"]

[dependencies.tracing]
version = "0.1"
optional = true
features = ["release_max_level_off"]

[features]
tracing = ["dep:tracing"]
